// Hand-written wired notify registry — Task 9. Imports the DATA half generated by Task 7
// (src/generated/notify/registry.data.ts's ADAPTERS) and attaches each adapter's real
// implementation (src/notify/impl/*.ts), pinning every `impl` with
// `satisfies NotifyAdapter<Payload[, Digest]>` against the SAME payload types the metaobjects
// model declares for that adapter (adapter.notify's @payloadRef/@digestPayloadRef in
// metaobjects/meta.notify.json -> ADAPTERS[name].payloadRef/digestPayloadRef).
//
// This is the drift-safety point carried over from Task 7's review: if a payload VO's fields
// ever change, `meta gen` regenerates AlertPayload/DigestPayload/HeartbeatPayload and this
// file's `satisfies` pins make a now-nonconforming impl fail `tsc --noEmit` immediately, instead
// of silently shipping a stale shape. Proof (see task-9-report.md): temporarily narrowing
// AlertPayload's `kind` (a local edit, reverted) makes `stdoutAdapter satisfies
// NotifyAdapter<AlertPayload, DigestPayload>` below fail to compile.
//
// kuma is deliberately NOT given a digestPayloadRef/second type param — it's heartbeat-only
// (see kuma.ts's header and ADAPTERS.kuma in registry.data.ts, which has no digestPayloadRef).

import { ADAPTERS } from "../generated/notify/registry.data";
import type { NotifyAdapter, AdapterName } from "../generated/notify/registry.data";
import type { AlertPayload, DigestPayload, HeartbeatPayload } from "../generated";
import { stdoutAdapter } from "./impl/stdout";
import { haPushAdapter } from "./impl/ha-push";
import { kumaAdapter } from "./impl/kuma";
import { matrixAdapter } from "./impl/matrix";
import { emailAdapter } from "./impl/email";

export const REGISTRY = {
  email: { ...ADAPTERS.email, impl: emailAdapter satisfies NotifyAdapter<AlertPayload, DigestPayload> },
  "ha-push": {
    ...ADAPTERS["ha-push"],
    impl: haPushAdapter satisfies NotifyAdapter<AlertPayload, DigestPayload>,
  },
  kuma: { ...ADAPTERS.kuma, impl: kumaAdapter satisfies NotifyAdapter<HeartbeatPayload> },
  matrix: { ...ADAPTERS.matrix, impl: matrixAdapter satisfies NotifyAdapter<AlertPayload, DigestPayload> },
  stdout: { ...ADAPTERS.stdout, impl: stdoutAdapter satisfies NotifyAdapter<AlertPayload, DigestPayload> },
} as const;

export type { NotifyAdapter, AdapterName };
export { ADAPTERS, missingAdapterConfig } from "../generated/notify/registry.data";
